name: Generate Domains JSON

on:
  push:
    branches:
      - main   # Replace with your target branch name

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14   # Adjust the version as needed

    - name: Install dependencies
      run: npm install    # If you have package.json and dependencies

    - name: Generate domains.json
      run: node sort.js   # Make sure sort.js is in the repository root

    - name: Configure Git
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "Github Action"

    - name: Commit files
      run: |
        git add domains.json
        git commit -m "Add domains.json"

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.PAT }}
        repository: Test/test
        force: true
