name: Process Domains

on:
  push:
    branches:
      - main # Change to your main branch name
  pull_request:
    branches:
      - main # Change to your main branch name

jobs:
  process_domains:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        persist-credentials: true # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
        fetch-depth: 0
        node-version: 14 # Choose the appropriate Node.js version

    - name: Install dependencies
      run: npm install

    - name: Run the script
      run: node script/json.js # Replace with the actual filename

    - name: Commit and push changes
      run: |
        git config --local user.name "Github Action"
        git config --local user.email "action@github.com"
        git add domains.json
        git commit -a -m "Generated domains.js"

    - name: Push changes
      uses: ad-m/github-push-action@master
      continue-on-error: true
      with:
         github_token: ${{ secrets.PAT }}
      
    - name: Complete
      run: echo "Script execution complete"
